# Build a small sqlx-cli image locally
FROM rust:1.89-alpine3.20 AS builder
RUN apk add --no-cache musl-dev
RUN cargo install sqlx-cli --no-default-features --features rustls,postgres

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=builder /usr/local/cargo/bin/sqlx /usr/local/bin/sqlx
WORKDIR /work
ENTRYPOINT ["sqlx"]